export const LOAD_CLASSES_REQUEST = "LOAD_CLASSES_REQUEST";
export const LOAD_CLASSES_SUCCESS = "SET_CLASSES_SUCCESS";
export const LOAD_CLASSES_ERROR = "ERROR_CLASSES_REQUEST";
export const LOAD_LESSONS_BY_CLASS_ID_REQUEST = "LOAD_LESSONS_BY_CLASS_ID_REQUEST"
export const LOAD_LESSONS_BY_CLASS_ID_SUCCESS = "LOAD_LESSONS_BY_CLASS_ID_SUCCESS"
export const LOAD_LESSONS_BY_CLASS_ID_ERROR = "LOAD_LESSONS_BY_CLASS_ID_ERROR"
export const TOGGLE_USER_MENU = "TOGGLE_USER_MENU"